<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="16846" started-at="2018-03-16T11:05:08Z" finished-at="2018-03-16T11:05:25Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="16846" started-at="2018-03-16T11:05:08Z" finished-at="2018-03-16T11:05:25Z">
      <class name="tests.googleTest.tests.JavaTest">
        <test-method status="PASS" signature="setDriver()[pri:0, instance:tests.googleTest.tests.JavaTest@531be3c5]" name="setDriver" is-config="true" duration-ms="4882" started-at="2018-03-16T11:05:08Z" finished-at="2018-03-16T11:05:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setDriver -->
        <test-method status="PASS" signature="googleSearch()[pri:0, instance:tests.googleTest.tests.JavaTest@531be3c5]" name="googleSearch" duration-ms="2139" started-at="2018-03-16T11:05:13Z" finished-at="2018-03-16T11:05:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleSearch -->
        <test-method status="FAIL" signature="resultSearchTest()[pri:0, instance:tests.googleTest.tests.JavaTest@531be3c5]" name="resultSearchTest" duration-ms="11" started-at="2018-03-16T11:05:15Z" finished-at="2018-03-16T11:05:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[java - РџРѕРёСЃРє РІ Google expected [java - РџРѕРёСЃРє РІ Google] but found [java - Поиск в Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: java - РџРѕРёСЃРє РІ Google expected [java - РџРѕРёСЃРє РІ Google] but found [java - Поиск в Google]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at tests.googleTest.tests.JavaTest.resultSearchTest(JavaTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resultSearchTest -->
        <test-method status="PASS" signature="shutdown()[pri:0, instance:tests.googleTest.tests.JavaTest@531be3c5]" name="shutdown" is-config="true" duration-ms="1640" started-at="2018-03-16T11:05:15Z" finished-at="2018-03-16T11:05:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shutdown -->
      </class> <!-- tests.googleTest.tests.JavaTest -->
      <class name="tests.googleTest.tests.RubyTest">
        <test-method status="PASS" signature="setDriver()[pri:0, instance:tests.googleTest.tests.RubyTest@52af6cff]" name="setDriver" is-config="true" duration-ms="4425" started-at="2018-03-16T11:05:17Z" finished-at="2018-03-16T11:05:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setDriver -->
        <test-method status="PASS" signature="googleSearch()[pri:0, instance:tests.googleTest.tests.RubyTest@52af6cff]" name="googleSearch" duration-ms="2186" started-at="2018-03-16T11:05:21Z" finished-at="2018-03-16T11:05:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleSearch -->
        <test-method status="FAIL" signature="resultSearchTest()[pri:0, instance:tests.googleTest.tests.RubyTest@52af6cff]" name="resultSearchTest" duration-ms="9" started-at="2018-03-16T11:05:23Z" finished-at="2018-03-16T11:05:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Ruby - Поиск в Google] but found [Ruby - РџРѕРёСЃРє РІ Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Ruby - Поиск в Google] but found [Ruby - РџРѕРёСЃРє РІ Google]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at tests.googleTest.tests.RubyTest.resultSearchTest(RubyTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resultSearchTest -->
        <test-method status="PASS" signature="shutDown()[pri:0, instance:tests.googleTest.tests.RubyTest@52af6cff]" name="shutDown" is-config="true" duration-ms="1531" started-at="2018-03-16T11:05:23Z" finished-at="2018-03-16T11:05:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shutDown -->
      </class> <!-- tests.googleTest.tests.RubyTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
